import { Design, DesignRun } from './design.api';

/** A small design as the calc service returns it: one transformer, two LV branches, an MV line, one failed check, one placeholder. */
export function design(over: Partial<Design> = {}): Design {
  const trace = {
    value: 100,
    unit: 'kVA',
    formula_id: 'tx.size.v1',
    formula: 'S',
    clause: 'test',
    rules_hash: 'abc',
    inputs: [],
  };
  return {
    rules_ref: 'eskom/0.8.1',
    rules_hash: '0123456789abcdef',
    inputs_hash: 'fedcba9876543210',
    construction: 'overhead',
    lv: {
      network: {
        nodes: [
          {
            id: 'N1',
            kind: 'source',
            coordinates: [28.1, -25.52],
            label: 'TX1',
            candidate_id: 'c1',
            feeder: null,
            distance_m: 0,
          },
          {
            id: 'N2',
            kind: 'pole',
            coordinates: [28.101, -25.52],
            label: 'P1',
            candidate_id: null,
            feeder: 'TX1-F1',
            distance_m: 100,
          },
          {
            id: 'N3',
            kind: 'end',
            coordinates: [28.102, -25.52],
            label: null,
            candidate_id: null,
            feeder: 'TX1-F1',
            distance_m: 200,
          },
        ],
        branches: [
          {
            id: 'B1',
            kind: 'route',
            from_node: 'N1',
            to_node: 'N2',
            coordinates: [
              [28.1, -25.52],
              [28.101, -25.52],
            ],
            length_m: 100,
            candidate_id: 'r1',
            feeder: 'TX1-F1',
          },
          {
            id: 'B2',
            kind: 'route',
            from_node: 'N2',
            to_node: 'N3',
            coordinates: [
              [28.101, -25.52],
              [28.102, -25.52],
            ],
            length_m: 100,
            candidate_id: 'r1',
            feeder: 'TX1-F1',
          },
        ],
        feeders: [{ id: 'TX1-F1', source: 'N1', length_m: 200 }],
      },
      allocation: {
        allocations: [
          {
            load_id: 'l1',
            building_id: 'b1',
            label: '101',
            kind: 'residential',
            kva: 2,
            branch: 'B2',
            node: null,
            at: [28.1015, -25.52],
            service_m: 15,
            box: 'P1-1',
            feeder: 'TX1-F1',
            phase: 'R',
            location: [28.1015, -25.5199],
          },
        ],
      },
      analysis: {
        limit_pct: 5,
        points: [
          {
            id: 'N2',
            kind: 'node',
            feeder: 'TX1-F1',
            distance_m: 100,
            worst_pct: 3.0,
            fault_a: 900,
            passes: true,
          },
          {
            id: 'N3',
            kind: 'node',
            feeder: 'TX1-F1',
            distance_m: 200,
            worst_pct: 6.1,
            fault_a: 700,
            passes: false,
          },
        ],
        branches: [
          {
            id: 'B1',
            feeder: 'TX1-F1',
            conductor: 'ABC-70',
            rating_a: 200,
            utilisation_pct: 50,
            passes: true,
          },
          {
            id: 'B2',
            feeder: 'TX1-F1',
            conductor: 'ABC-70',
            rating_a: 200,
            utilisation_pct: 120,
            passes: false,
          },
        ],
      },
      sizing: { conductors: { 'TX1-F1': 'ABC-70' } },
      generated: 1,
    },
    overhead: { poles: [] },
    underground: null,
    transformers: {
      transformers: [
        {
          id: 'TX1',
          label: 'TX1',
          candidate_id: 'c1',
          coordinates: [28.1, -25.52],
          mounting: 'pole',
          feeders: 1,
          loads: 1,
          demand_kva: 40,
          rating_kva: 100,
          loading_pct: 40,
          spare_kva: 60,
          impedance_pct: 4,
          fixed: false,
          passes: true,
          trace,
        },
      ],
    },
    mv_network: {
      nodes: [
        {
          id: 'M1',
          kind: 'source',
          coordinates: [28.09, -25.52],
          label: 'CP',
          candidate_id: null,
          feeder: null,
          distance_m: 0,
        },
      ],
      branches: [
        {
          id: 'MB1',
          kind: 'route',
          from_node: 'M1',
          to_node: 'M2',
          coordinates: [
            [28.09, -25.52],
            [28.1, -25.52],
          ],
          length_m: 1000,
          candidate_id: 'm1',
          feeder: 'F1',
        },
      ],
      feeders: [],
    },
    mv: {
      construction: 'overhead',
      voltage_kv: 11,
      limit_pct: 5,
      total_kva: 40,
      branches: [
        {
          id: 'MB1',
          feeder: 'F1',
          conductor: 'HARE',
          length_m: 1000,
          demand_kva: 40,
          current_a: 2.1,
          rating_a: 200,
          utilisation_pct: 1,
          drop_pct: 0.1,
          passes: true,
        },
      ],
      taps: [],
    },
    mv_overhead: {
      poles: [
        {
          id: 'MP1',
          label: 'MP1',
          network: 'mv',
          coordinates: [28.095, -25.52],
          kind: 'suspension',
          height_m: 11,
          pole_class: 'S',
          stays: 0,
          generated: true,
          passes: true,
        },
      ],
    },
    bulk: { stopped: 'No connection point capacity and fault level from the authority.' },
    cost: {
      library: 'indicative',
      rate_date: '2026-01-01',
      indicative: true,
      currency: 'ZAR',
      capex: 100000,
      capex_low: 80000,
      capex_high: 120000,
      losses: { npv: 5000, energy_mwh_per_year: 3 },
      lifetime: 150000,
      lifetime_low: 120000,
      lifetime_high: 180000,
      lines: [
        {
          code: 'A-LV-OH',
          description: 'LV line',
          unit: 'm',
          qty: 200,
          rate: 120,
          amount: 24000,
          low: 20000,
          high: 28000,
          group: 'LV',
        },
      ],
    },
    comparison: [],
    checks: [
      {
        id: 'lv_drop:N2',
        category: 'lv_drop',
        element: 'N2',
        label: 'P1',
        value: 3,
        limit: 5,
        unit: '%',
        passes: true,
        clause: 'NRS 048-2',
        index: 'ESKOM-VDROP',
        formula_id: 'lv.vdrop.herman-beta.v1',
      },
      {
        id: 'lv_drop:N3',
        category: 'lv_drop',
        element: 'N3',
        label: null,
        value: 6.1,
        limit: 5,
        unit: '%',
        passes: false,
        clause: 'NRS 048-2',
        index: 'ESKOM-VDROP',
        formula_id: 'lv.vdrop.herman-beta.v1',
      },
      {
        id: 'tx_loading:TX1',
        category: 'tx_loading',
        element: 'TX1',
        label: 'TX1',
        value: 40,
        limit: 100,
        unit: '%',
        passes: true,
        clause: 'SANS 780',
        index: null,
        formula_id: 'tx.size.v1',
      },
    ],
    not_inspected: [{ candidate_id: 'c1', kind: 'transformer', label: 'TX1', elements: ['N1'] }],
    issues: [],
    placeholders: ['lv_design.max_drop_pct: PLACEHOLDER'],
    fit_to_submit: false,
    summary: {
      construction: 'overhead',
      loads: 1,
      connected: 1,
      transformers: 1,
      transformer_kva: 100,
      poles: 1,
      stays: 0,
      kiosks: 0,
      lv_km: 0.2,
      mv_km: 1,
      worst_lv_drop_pct: 6.1,
      worst_mv_drop_pct: 0.1,
      nmd_kva: null,
      capex: 100000,
      lifetime: 150000,
      spare_pct: 60,
      checks: 3,
      failures: 1,
    },
    ...over,
  };
}

export function run(over: Partial<DesignRun> = {}): DesignRun {
  return {
    id: 'r1',
    number: 1,
    mode: 'run',
    parentRunId: null,
    rulesRef: 'eskom/0.8.1',
    rulesHash: '0123456789abcdef',
    inputsHash: 'f'.repeat(64),
    resultHash: 'a'.repeat(64),
    construction: 'overhead',
    fitToSubmit: false,
    checks: 3,
    failures: 1,
    capex: 100000,
    lifetime: 150000,
    summary: null,
    createdAt: '2026-10-06T10:00:00Z',
    current: true,
    stale: null,
    ...over,
  };
}
